# Generated by Django 4.2.7 on 2023-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pepero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choco', models.TextField(verbose_name='초코코팅')),
                ('syrop', models.TextField(verbose_name='시럽')),
                ('deco', models.TextField(verbose_name='지불방식')),
                ('content', models.TextField(verbose_name='편지 내용')),
            ],
        ),
    ]
