# Generated by Django 4.2.7 on 2023-11-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pepero',
            name='syrop',
        ),
        migrations.AddField(
            model_name='pepero',
            name='sauce',
            field=models.TextField(blank=True, null=True, verbose_name='소스'),
        ),
        migrations.AlterField(
            model_name='pepero',
            name='choco',
            field=models.TextField(blank=True, null=True, verbose_name='초코'),
        ),
        migrations.AlterField(
            model_name='pepero',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='편지'),
        ),
        migrations.AlterField(
            model_name='pepero',
            name='deco',
            field=models.TextField(blank=True, null=True, verbose_name='데코'),
        ),
    ]
