# Generated by Django 4.2.7 on 2023-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepero', '0002_remove_pepero_syrop_pepero_sauce_alter_pepero_choco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pepero',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='타이틀'),
        ),
    ]
