# Generated by Django 4.2.4 on 2023-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepero', '0004_pepero_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
